### ISSUE TITLE
Tray icon looks great on default GNOME theme, but not others

### ISSUE THREAD

**Issue by jamielinux** [lmacken/gnome-shell-extension-fedmsg#2]
Cool bus!

But when using other GNOME themes (yum install gnome-shell-themes-*), the top bar often changes colour and height. So sometimes the bus icon is too tall for the top bar and extends below. And other times the bus stands out like a sore thumb with a black square around it. (Other icons seem to have a transparent background.)

Sadly I couldn't find any upstream guidelines for gnome shell extension development or icon guidelines.

**Comment by audreytoskin** [comment]
Still an issue when installing the extension for GNOME 3.22.

**Comment by audreytoskin** [comment]
Using a flat white bus image on a transparent background might also be problematic if the panel color is light, or if the panel is transparent and the wallpaper is a light color. Then, instead of sticking out too much, but the fedmsg icon would be hard to see at all. What might be better is if the bus image had a black outline instead of a black background.

If anyone's still maintaining this project, I could send a pull request fixing this issue. This repo hasn't gotten any commits in a while, though.
